## netify
[build]
  command = "npm run build-storybook && npx sb extract storybook-static"
  publish = "storybook-static/"

[[headers]]
  for = "/stories.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/metadata.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/